# Publishing a Data Product on AWS

## Instructions

In this exercise, you will be adding a Serving Layer to the database

You will be creating a Customer Facing View that will provide the customer with a more user friendly view of the output










# Data Contract

Use the Data Contract and ERD provided below to guide you.

---

In [ ]:

{
  "contract_name": "Big Box Store Retail Operations Data Contract",
  "version": "1.0",
  "description": "Data contract defining customers, orders, inventory, payment types, distribution centers, and order items for a big box retail store.",
  "tables": [
    {
      "table_name": "Customers",
      "description": "Customer information for individuals or businesses placing orders.",
      "columns": [
        {
          "name": "customer_id",
          "data_type": "string",
          "required": true,
          "pattern": "^CUS[0-9]{6}$"
        },
        {
          "name": "first_name",
          "data_type": "string",
          "required": true,
          "max_length": 50
        },
        {
          "name": "last_name",
          "data_type": "string",
          "required": true,
          "max_length": 50
        },
        {
          "name": "email",
          "data_type": "string",
          "required": true,
          "format": "email"
        },
        {
          "name": "phone",
          "data_type": "string",
          "required": false
        },
        {
          "name": "loyalty_member_flag",
          "data_type": "boolean",
          "required": true
        }
      ]
    },
    {
      "table_name": "Distribution_Center",
      "description": "Distribution centers that store and ship inventory.",
      "columns": [
        {
          "name": "distribution_center_id",
          "data_type": "string",
          "required": true,
          "pattern": "^DC[0-9]{4}$"
        },
        {
          "name": "distribution_center_name",
          "data_type": "string",
          "required": true,
          "max_length": 100
        },
        {
          "name": "city",
          "data_type": "string",
          "required": true,
          "max_length": 75
        },
        {
          "name": "state",
          "data_type": "string",
          "required": true,
          "pattern": "^[A-Z]{2}$"
        },
        {
          "name": "region",
          "data_type": "string",
          "required": true,
          "allowed_values": [
            "Northeast",
            "Southeast",
            "Midwest",
            "Southwest",
            "West"
          ]
        }
      ]
    },
    {
      "table_name": "Inventory",
      "description": "Products available for sale and their current stock levels.",
      "columns": [
        {
          "name": "inventory_id",
          "data_type": "string",
          "required": true,
          "pattern": "^INV[0-9]{6}$"
        },
        {
          "name": "product_name",
          "data_type": "string",
          "required": true,
          "max_length": 150
        },
        {
          "name": "product_category",
          "data_type": "string",
          "required": true,
          "allowed_values": [
            "Appliances",
            "Electronics",
            "Home Goods",
            "Hardware",
            "Outdoor",
            "Grocery",
            "Clothing",
            "Automotive"
          ]
        },
        {
          "name": "unit_price",
          "data_type": "decimal",
          "required": true,
          "minimum": 0.01
        },
        {
          "name": "quantity_on_hand",
          "data_type": "integer",
          "required": true,
          "minimum": 0
        },
        {
          "name": "distribution_center_id",
          "data_type": "string",
          "required": true,
          "foreign_key": {
            "table": "Distribution_Center",
            "column": "distribution_center_id"
          }
        }
      ]
    },
    {
      "table_name": "Payment_Types",
      "description": "Accepted payment methods for customer orders.",
      "columns": [
        {
          "name": "payment_type_id",
          "data_type": "string",
          "required": true,
          "pattern": "^PAY[0-9]{3}$"
        },
        {
          "name": "payment_type_name",
          "data_type": "string",
          "required": true,
          "allowed_values": [
            "Credit Card",
            "Debit Card",
            "Store Card",
            "Gift Card",
            "Cash",
            "Digital Wallet"
          ]
        },
        {
          "name": "payment_provider",
          "data_type": "string",
          "required": false,
          "max_length": 75
        }
      ]
    },
    {
      "table_name": "Orders",
      "description": "Customer order header records.",
      "columns": [
        {
          "name": "order_id",
          "data_type": "string",
          "required": true,
          "pattern": "^ORD[0-9]{7}$"
        },
        {
          "name": "order_date",
          "data_type": "date",
          "required": true
        },
        {
          "name": "customer_id",
          "data_type": "string",
          "required": true,
          "foreign_key": {
            "table": "Customers",
            "column": "customer_id"
          }
        },
        {
          "name": "payment_type_id",
          "data_type": "string",
          "required": true,
          "foreign_key": {
            "table": "Payment_Types",
            "column": "payment_type_id"
          }
        },
        {
          "name": "order_channel",
          "data_type": "string",
          "required": true,
          "allowed_values": [
            "In Store",
            "Online",
            "Mobile App",
            "Curbside Pickup"
          ]
        },
        {
          "name": "order_status",
          "data_type": "string",
          "required": true,
          "allowed_values": [
            "Pending",
            "Processing",
            "Shipped",
            "Completed",
            "Cancelled",
            "Returned"
          ]
        },
        {
          "name": "order_total",
          "data_type": "decimal",
          "required": true,
          "minimum": 0
        }
      ]
    },
    {
      "table_name": "Order_Items",
      "description": "Line-level products included in each order.",
      "columns": [
        {
          "name": "order_item_id",
          "data_type": "string",
          "required": true,
          "pattern": "^ITEM[0-9]{7}$"
        },
        {
          "name": "order_id",
          "data_type": "string",
          "required": true,
          "foreign_key": {
            "table": "Orders",
            "column": "order_id"
          }
        },
        {
          "name": "inventory_id",
          "data_type": "string",
          "required": true,
          "foreign_key": {
            "table": "Inventory",
            "column": "inventory_id"
          }
        },
        {
          "name": "quantity_ordered",
          "data_type": "integer",
          "required": true,
          "minimum": 1
        },
        {
          "name": "unit_price_at_purchase",
          "data_type": "decimal",
          "required": true,
          "minimum": 0.01
        },
        {
          "name": "line_total",
          "data_type": "decimal",
          "required": true,
          "minimum": 0.01
        }
      ]
    }
  ],
  "business_rules": [
    "Every order must be associated with a valid customer.",
    "Every order must use a valid payment type.",
    "Every inventory item must be assigned to a valid distribution center.",
    "Every order item must reference a valid order and inventory item.",
    "Quantity ordered must be greater than zero.",
    "Unit price and line total must be positive values.",
    "Quantity on hand cannot be negative.",
    "Order total should equal the sum of line totals for the order.",
    "Customer email addresses should be unique.",
    "Distribution center state must use a valid two-letter state abbreviation."
  ]
}

```mermaid
erDiagram

    customers {
        varchar customer_id PK
        varchar first_name
        varchar last_name
        varchar email
        varchar phone
        boolean loyalty_member_flag
    }

    distribution_center {
        varchar distribution_center_id PK
        varchar distribution_center_name
        varchar city
        char state
        varchar region
    }

    inventory {
        varchar inventory_id PK
        varchar product_name
        varchar product_category
        numeric unit_price
        integer quantity_on_hand
        varchar distribution_center_id FK
    }

    payment_types {
        varchar payment_type_id PK
        varchar payment_type_name
        varchar payment_provider
    }

    orders {
        varchar order_id PK
        date order_date
        varchar customer_id FK
        varchar payment_type_id FK
        varchar order_channel
        varchar order_status
        numeric order_total
    }

    order_items {
        varchar order_item_id PK
        varchar order_id FK
        varchar inventory_id FK
        integer quantity_ordered
        numeric unit_price_at_purchase
        numeric line_total
    }

    customers ||--o{ orders : places
    payment_types ||--o{ orders : used_for
    distribution_center ||--o{ inventory : stores
    orders ||--o{ order_items : contains
    inventory ||--o{ order_items : included_in

## Connect to AWS

In [ ]:
import boto3
import json
import psycopg2
import pandas as pd
from psycopg2.extras import execute_values


AWS_ACCESS_KEY_ID = "<get key from classroom>"
AWS_SECRET_ACCESS_KEY = "<get key from classroom>"
AWS_SESSION_TOKEN = "<get key from classroom>"
AWS_REGION = "us-east-1"

session = boto3.Session(
    aws_access_key_id=AWS_ACCESS_KEY_ID,
    aws_secret_access_key=AWS_SECRET_ACCESS_KEY,
    aws_session_token=AWS_SESSION_TOKEN,
    region_name=AWS_REGION,
)


# Get DB connection info from CloudFormation
cf = session.client("cloudformation")
stack = cf.describe_stacks()["Stacks"][0]
outputs = {o["OutputKey"]: o["OutputValue"] for o in stack["Outputs"]}

db_host = outputs["DBEndpoint"]
db_port = int(outputs["DBPort"])
db_name = outputs["DBName"]
secret_arn = outputs["MasterSecretArn"]

# Get credentials from Secrets Manager
sm = session.client("secretsmanager", region_name="us-east-1")
secret_response = sm.get_secret_value(SecretId=secret_arn)
db_secret = json.loads(secret_response["SecretString"])

# Connect to DB
try:
    conn = psycopg2.connect(
        host=db_host,
        port=db_port,
        dbname=db_name,
        user=db_secret["username"],
        password=db_secret["password"],
        sslmode="require",
    )
    print("Successfully connected to the database")
 
except Exception as e:
    print(f"Connection failed: {type(e).__name__}: {e}")

Successfully connected to the database

### Build Database from Starter Code

Using the provided starter code:

Connect to AWS

Build Databases

Populate Database

---

### Create Tables

In [9]:
# Create normalized tables for the Big Box Store database
conn.rollback()
cur = conn.cursor()
create_tables_sql = """
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS payment_types CASCADE;
DROP TABLE IF EXISTS distribution_center CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
CREATE TABLE customers (
    customer_id VARCHAR(20) PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(25),
    loyalty_member_flag BOOLEAN NOT NULL
);
CREATE TABLE distribution_center (
    distribution_center_id VARCHAR(20) PRIMARY KEY,
    distribution_center_name VARCHAR(100) NOT NULL,
    city VARCHAR(75) NOT NULL,
    state CHAR(2) NOT NULL,
    region VARCHAR(20) NOT NULL
);
CREATE TABLE payment_types (
    payment_type_id VARCHAR(20) PRIMARY KEY,
    payment_type_name VARCHAR(50) NOT NULL,
    payment_provider VARCHAR(75)
);
CREATE TABLE inventory (
    inventory_id VARCHAR(20) PRIMARY KEY,
    product_name VARCHAR(150) NOT NULL,
    product_category VARCHAR(50) NOT NULL,
    unit_price NUMERIC(10,2) NOT NULL,
    quantity_on_hand INTEGER NOT NULL,
    distribution_center_id VARCHAR(20) NOT NULL,
    CONSTRAINT fk_inventory_distribution_center
        FOREIGN KEY (distribution_center_id)
        REFERENCES distribution_center(distribution_center_id),
    CONSTRAINT chk_inventory_price
        CHECK (unit_price > 0),
    CONSTRAINT chk_inventory_quantity
        CHECK (quantity_on_hand >= 0)
);
CREATE TABLE orders (
    order_id VARCHAR(20) PRIMARY KEY,
    order_date DATE NOT NULL,
    customer_id VARCHAR(20) NOT NULL,
    payment_type_id VARCHAR(20) NOT NULL,
    order_channel VARCHAR(50) NOT NULL,
    order_status VARCHAR(50) NOT NULL,
    order_total NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id)
        REFERENCES customers(customer_id),
    CONSTRAINT fk_orders_payment_type
        FOREIGN KEY (payment_type_id)
        REFERENCES payment_types(payment_type_id),
    CONSTRAINT chk_order_total
        CHECK (order_total >= 0)
);
CREATE TABLE order_items (
    order_item_id VARCHAR(20) PRIMARY KEY,
    order_id VARCHAR(20) NOT NULL,
    inventory_id VARCHAR(20) NOT NULL,
    quantity_ordered INTEGER NOT NULL,
    unit_price_at_purchase NUMERIC(10,2) NOT NULL,
    line_total NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id)
        REFERENCES orders(order_id),
    CONSTRAINT fk_order_items_inventory
        FOREIGN KEY (inventory_id)
        REFERENCES inventory(inventory_id),
    CONSTRAINT chk_quantity_ordered
        CHECK (quantity_ordered > 0),
    CONSTRAINT chk_purchase_price
        CHECK (unit_price_at_purchase > 0),
    CONSTRAINT chk_line_total
        CHECK (line_total > 0)
);
"""
cur.execute(create_tables_sql)
conn.commit()
cur.close()
print("Big Box Store tables created successfully.")

Big Box Store tables created successfully.

### Load CSV files into memory

In [ ]:
# Read CSV files
customers_df = pd.read_csv("../serving-layer-exercise/customers.csv")
distribution_center_df = pd.read_csv("../serving-layer-exercise/distribution_center.csv")
payment_types_df = pd.read_csv("../serving-layer-exercise/payment_types.csv")
inventory_df = pd.read_csv("../serving-layer-exercise/inventory.csv")
orders_df = pd.read_csv("../serving-layer-exercise/orders.csv")
order_items_df = pd.read_csv("../serving-layer-exercise/order_items.csv")

print("customers:", len(customers_df))
print("distribution_center:", len(distribution_center_df))
print("payment_types:", len(payment_types_df))
print("inventory:", len(inventory_df))
print("orders:", len(orders_df))
print("order_items:", len(order_items_df))

### Insert Data into tables

In [ ]:
conn.rollback()
cur = conn.cursor()

tables = [
    (
        "customers",
        ["customer_id", "first_name", "last_name", "email", "phone", "loyalty_member_flag"],
        customers_df,
        lambda row: (row.customer_id, row.first_name, row.last_name, row.email, row.phone, bool(row.loyalty_member_flag))
    ),
    (
        "distribution_center",
        ["distribution_center_id", "distribution_center_name", "city", "state", "region"],
        distribution_center_df,
        lambda row: (row.distribution_center_id, row.distribution_center_name, row.city, row.state, row.region)
    ),
    (
        "payment_types",
        ["payment_type_id", "payment_type_name", "payment_provider"],
        payment_types_df,
        lambda row: (row.payment_type_id, row.payment_type_name, row.payment_provider)
    ),
    (
        "inventory",
        ["inventory_id", "product_name", "product_category", "unit_price", "quantity_on_hand", "distribution_center_id"],
        inventory_df,
        lambda row: (row.inventory_id, row.product_name, row.product_category, float(row.unit_price), int(row.quantity_on_hand), row.distribution_center_id)
    ),
    (
        "orders",
        ["order_id", "order_date", "customer_id", "payment_type_id", "order_channel", "order_status", "order_total"],
        orders_df,
        lambda row: (row.order_id, row.order_date, row.customer_id, row.payment_type_id, row.order_channel, row.order_status, float(row.order_total))
    ),
    (
        "order_items",
        ["order_item_id", "order_id", "inventory_id", "quantity_ordered", "unit_price_at_purchase", "line_total"],
        order_items_df,
        lambda row: (row.order_item_id, row.order_id, row.inventory_id, int(row.quantity_ordered), float(row.unit_price_at_purchase), float(row.line_total))
    ),
]

for table, cols, df, row_fn in tables:
    sql = f"INSERT INTO {table} ({', '.join(cols)}) VALUES %s;"
    values = [row_fn(row) for row in df.itertuples(index=False)]
    execute_values(cur, sql, values)

conn.commit()
cur.close()
print("Data loaded.")

### Validate Data Load

In [ ]:
# Validate row counts

cur = conn.cursor()

cur.execute("""
SELECT 'customers' AS table_name, COUNT(*) FROM customers
UNION ALL
SELECT 'distribution_center', COUNT(*) FROM distribution_center
UNION ALL
SELECT 'payment_types', COUNT(*) FROM payment_types
UNION ALL
SELECT 'inventory', COUNT(*) FROM inventory
UNION ALL
SELECT 'orders', COUNT(*) FROM orders
UNION ALL
SELECT 'order_items', COUNT(*) FROM order_items;
""")

for row in cur.fetchall():
    print(row)

cur.close()


### Create Customer Facing View

Create a view that will display order information in a customer friendly format

This will be way the customer interacts with the database instead of viewing the underlying tables

---

In [12]:
conn.rollback()
cur = conn.cursor()
cur.execute("""
CREATE OR REPLACE VIEW vw_customer_order_summary AS
SELECT
    o.order_id,
    o.order_date,
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.email,
    o.order_channel,
    o.order_status,
    pt.payment_type_name,
    o.order_total
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
JOIN payment_types pt
    ON o.payment_type_id = pt.payment_type_id;
""")
conn.commit()
cur.close()
print("Serving layer view created.")


df = pd.read_sql("SELECT * FROM vw_customer_order_summary LIMIT 10;", conn)
display(df)

Serving layer view created.

/tmp/ipykernel_19/663458740.py:26: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM vw_customer_order_summary LIMIT 10;", conn)

,order_id,order_date,customer_id,customer_name,email,order_channel,order_status,payment_type_name,order_total
0,ORD0000001,2025-08-04,CUS000173,First173 Last173,customer173@example.com,Online,Cancelled,Credit Card,1017.54
1,ORD0000002,2025-10-16,CUS000104,First104 Last104,customer104@example.com,Mobile App,Pending,Store Card,1722.89
2,ORD0000003,2025-02-14,CUS000172,First172 Last172,customer172@example.com,Online,Processing,Credit Card,8324.42
3,ORD0000004,2025-05-03,CUS000083,First83 Last83,customer83@example.com,In Store,Shipped,Credit Card,3291.97
4,ORD0000005,2025-01-27,CUS000061,First61 Last61,customer61@example.com,Mobile App,Shipped,Store Card,9031.17
5,ORD0000006,2024-11-05,CUS000150,First150 Last150,customer150@example.com,In Store,Shipped,Digital Wallet,8356.57
6,ORD0000007,2025-10-31,CUS000093,First93 Last93,customer93@example.com,Online,Pending,Digital Wallet,3813.72
7,ORD0000008,2025-11-14,CUS000031,First31 Last31,customer31@example.com,Mobile App,Processing,Store Card,5998.41
8,ORD0000009,2025-02-19,CUS000176,First176 Last176,customer176@example.com,Mobile App,Returned,Gift Card,15589.15
9,ORD0000010,2024-04-30,CUS000164,First164 Last164,customer164@example.com,Mobile App,Cancelled,Debit Card,8949.08

### Alter Underlying Tables

Alter an underlying table in your view by adding a column to demostrate that your view is not affected by changes to the base table

---

In [13]:
conn.rollback()
cur = conn.cursor()

cur.execute("""
ALTER TABLE orders
ADD COLUMN IF NOT EXISTS fulfillment_priority VARCHAR(20)
DEFAULT 'Standard';
""")

conn.commit()
cur.close()

print("Internal table changed.")

df = pd.read_sql("SELECT * FROM vw_customer_order_summary LIMIT 10;", conn)
display(df)

Internal table changed.

/tmp/ipykernel_19/3776603432.py:15: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM vw_customer_order_summary LIMIT 10;", conn)

,order_id,order_date,customer_id,customer_name,email,order_channel,order_status,payment_type_name,order_total
0,ORD0000001,2025-08-04,CUS000173,First173 Last173,customer173@example.com,Online,Cancelled,Credit Card,1017.54
1,ORD0000002,2025-10-16,CUS000104,First104 Last104,customer104@example.com,Mobile App,Pending,Store Card,1722.89
2,ORD0000003,2025-02-14,CUS000172,First172 Last172,customer172@example.com,Online,Processing,Credit Card,8324.42
3,ORD0000004,2025-05-03,CUS000083,First83 Last83,customer83@example.com,In Store,Shipped,Credit Card,3291.97
4,ORD0000005,2025-01-27,CUS000061,First61 Last61,customer61@example.com,Mobile App,Shipped,Store Card,9031.17
5,ORD0000006,2024-11-05,CUS000150,First150 Last150,customer150@example.com,In Store,Shipped,Digital Wallet,8356.57
6,ORD0000007,2025-10-31,CUS000093,First93 Last93,customer93@example.com,Online,Pending,Digital Wallet,3813.72
7,ORD0000008,2025-11-14,CUS000031,First31 Last31,customer31@example.com,Mobile App,Processing,Store Card,5998.41
8,ORD0000009,2025-02-19,CUS000176,First176 Last176,customer176@example.com,Mobile App,Returned,Gift Card,15589.15
9,ORD0000010,2024-04-30,CUS000164,First164 Last164,customer164@example.com,Mobile App,Cancelled,Debit Card,8949.08

### Add Logic Layer to View

Modify your view to add a WHERE clause that provides added logic to your view without altering the look of output columns for the customer

---

In [ ]:
conn.rollback()
cur = conn.cursor()

cur.execute("""
CREATE OR REPLACE VIEW vw_customer_order_summary AS
SELECT
    o.order_id,
    o.order_date,
    c.customer_id,
    c.first_name || ' ' || c.last_name AS customer_name,
    c.email,
    o.order_channel,
    o.order_status,
    pt.payment_type_name,
    o.order_total
FROM orders o
JOIN customers c
    ON o.customer_id = c.customer_id
JOIN payment_types pt
    ON o.payment_type_id = pt.payment_type_id
WHERE o.order_status <> 'Cancelled';
""")

conn.commit()
cur.close()

print("Serving layer view updated internally.")

df = pd.read_sql("SELECT * FROM vw_customer_order_summary LIMIT 10;", conn)
display(df)


## Deliverables

Submit: Your ipynb file